import { useEffect, useState, type ReactNode } from 'react'
import { Activity, ArrowUpRight, Bot, CheckCircle2, ChevronRight, Clock3, Code2, FolderKanban, LayoutDashboard, Megaphone, Plus, Search, Send, ShieldCheck, Sparkles, UsersRound, Workflow } from 'lucide-react'
import './App.css'

type Page = 'Overview' | 'Projects' | 'AI Office' | 'Delivery' | 'Marketing'
const nav: [Page, typeof LayoutDashboard][] = [['Overview', LayoutDashboard], ['Projects', FolderKanban], ['AI Office', UsersRound], ['Delivery', Workflow], ['Marketing', Megaphone]]
const initialTasks = [
  ['Turn discovery notes into a product brief', 'Maya', 'In progress', 'Strategy'],
  ['Map architecture and service boundaries', 'Orion', 'Review', 'Architecture'],
  ['Create onboarding flow', 'Nova', 'In progress', 'Design'],
  ['Implement workspace API', 'Atlas', 'Ready', 'Engineering'],
]
const team = [['Maya', 'Chief of staff', 'Planning', '#997bf4'], ['Orion', 'Solutions architect', 'Reviewing', '#38bdf8'], ['Nova', 'Product designer', 'Designing', '#f472b6'], ['Atlas', 'Lead engineer', 'Building', '#34d399'], ['Quinn', 'Quality & security', 'Testing', '#fbbf24']]
const API_URL = 'http://127.0.0.1:8000/api'

export default function App() {
  const [page, setPage] = useState<Page>('Overview'), [prompt, setPrompt] = useState(''), [brief, setBrief] = useState(''), [notice, setNotice] = useState(''), [online, setOnline] = useState(false), [tasks, setTasks] = useState(initialTasks)
  useEffect(() => { fetch(`${API_URL}/status`).then(async r => { if (!r.ok) throw new Error('API unavailable'); setOnline(true); const stored = await fetch(`${API_URL}/tasks`).then(response => response.json()); if (stored.length) setTasks(stored.map((task: { title: string, owner?: string, status: string, department: string }) => [task.title, task.owner || 'Unassigned', task.status.replace('_', ' '), task.department])) }).catch(() => undefined) }, [])
  function send() { if (!prompt.trim()) return; setNotice(`Sent to your AI office: “${prompt.trim()}”`); setPrompt('') }
  async function createProject() { const clean = brief.trim(); if (!clean) return setNotice('Describe the work you would like your office to deliver.'); const name = clean.split(/[.!?]/)[0].slice(0, 60); try { const project = await fetch(`${API_URL}/projects`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, brief: clean }) }).then(response => { if (!response.ok) throw new Error('Project request failed'); return response.json() }); await fetch(`${API_URL}/tasks`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: 'Create delivery plan', project_id: project.id, owner: 'Maya', department: 'Strategy' }) }); setOnline(true) } catch { setOnline(false) } setTasks(t => [[clean, 'Maya', 'Ready', 'New request'], ...t]); setBrief(''); setNotice('Brief received. Maya is preparing the delivery plan.') }
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span><Sparkles size={18}/></span>AI Softwear<br/><b>Company</b></div><div className="workspace"><i>AS</i><div><small>WORKSPACE</small>Acme product studio</div><ChevronRight size={16}/></div><nav>{nav.map(([name, Icon]) => <button className={page === name ? 'active' : ''} onClick={() => setPage(name)} key={name}><Icon size={18}/>{name}{name === 'AI Office' && <em>5</em>}</button>)}</nav><div className="side-bottom"><button><ShieldCheck size={18}/>Settings</button><div className="upgrade"><Sparkles size={16}/><b>Scale your studio</b><span>Add projects and AI teammates.</span><a>View plans <ArrowUpRight size={12}/></a></div><div className="user"><i>JS</i><span>Jordan Smith<small>Studio owner</small></span></div></div></aside>
    <main><header><div><p>WORKSPACE / {page.toUpperCase()}</p><h1>{page === 'Overview' ? 'Good morning, Jordan.' : page}</h1></div><div className="header-actions"><label><Search size={16}/><input placeholder="Search workspace"/></label><button className="new" onClick={() => setPage('Projects')}><Plus size={16}/>New project</button></div></header>
      <div className="command"><span><Sparkles size={18}/></span><input value={prompt} onChange={e => setPrompt(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask your AI office anything — plan, build, review, or ship..."/><button onClick={send}><Send size={16}/></button></div>{notice && <div className="notice"><CheckCircle2 size={16}/>{notice}<b onClick={() => setNotice('')}>×</b></div>}
      {page === 'Overview' && <Overview tasks={tasks}/>} {page === 'Projects' && <Projects brief={brief} setBrief={setBrief} create={createProject} tasks={tasks}/>} {page === 'AI Office' && <Office/>} {page === 'Delivery' && <Delivery tasks={tasks}/>} {page === 'Marketing' && <Marketing/>}
      <footer>AI Softwear Company OS · v1.0 <span className={online ? 'online' : 'demo'}><i/>{online ? 'Backend connected' : 'Demo workspace'}</span></footer></main></div>
}
function Overview({ tasks }: { tasks: string[][] }) { return <><section className="metrics"><Metric icon={<FolderKanban/>} name="Active projects" value="03" detail="2 are on track"/><Metric icon={<Activity/>} name="Open tasks" value={`0${tasks.length}`} detail="4 due this week"/><Metric icon={<Bot/>} name="Office velocity" value="94%" detail="↑ 12% from last week"/><Metric icon={<ShieldCheck/>} name="Quality score" value="98" detail="All gates passing"/></section><section className="split"><article className="panel pulse"><Title text="Delivery pulse" action="View board"/><div className="project"><i><Code2 size={21}/></i><div><b>Acme customer portal</b><small>Web app · Sprint 04</small></div><em>• On track</em></div><div className="progress-title">Release readiness <b>72%</b></div><div className="progress"><i/></div><div className="milestones"><b>✓ Brief</b><b>✓ Design</b><strong>Build</strong><span>QA</span><span>Ship</span></div></article><article className="panel"><Title text="Office activity" action="All activity"/><div className="activity"><Row who="A" color="green" text="Atlas completed API authentication" time="8 min ago"/><Row who="Q" color="gold" text="Quinn started a security review" time="23 min ago"/><Row who="N" color="pink" text="Nova shared 3 new screens" time="1 hr ago"/><Row who="M" color="purple" text="Maya created the sprint plan" time="2 hr ago"/></div></article></section><article className="panel tasks"><Title text="Your priority queue" action="Open tasks"/><div className="table head"><span>WORK ITEM</span><span>OWNER</span><span>STATUS</span><span>AREA</span></div>{tasks.map((t,i)=><div className="table" key={i}><span><i className="check"/>{t[0]}</span><span><i className="owner">{t[1][0]}</i>{t[1]}</span><span><b className={'status '+t[2].replace(' ','').toLowerCase()}>{t[2]}</b></span><span><em className="tag">{t[3]}</em></span></div>)}</article></> }
function Projects({brief,setBrief,create,tasks}:{brief:string,setBrief:(s:string)=>void,create:()=>void,tasks:string[][]}) { return <section className="split projects"><article className="panel intake"><p><Sparkles size={14}/> START A NEW ENGAGEMENT</p><h2>What should the office build?</h2><span>Describe the outcome. Your AI team will turn it into a scoped plan, team assignments, and delivery board.</span><textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Example: Build a client portal where customers can track orders, manage invoices, and contact support."/><button className="primary" onClick={create}>Create project brief <ArrowUpRight size={16}/></button></article><article className="panel"><Title text="Current engagements" action="Manage"/><Engage title="Acme customer portal" text="Build · 72% complete" due="Due Sep 12"/><Engage title="Northstar mobile app" text="Discovery · 18% complete" due="Due Oct 04"/><Engage title="AI Softwear rebrand" text="Marketing · 54% complete" due="Due Sep 02"/><p className="muted">{tasks.length} work items are being coordinated across your office.</p></article></section> }
function Office(){return <section className="office"><div className="office-head"><div><p>YOUR AI TEAM</p><h2>A focused team that never loses context.</h2><span>Each specialist works from the same brief, standards, and delivery plan.</span></div><button className="new"><Plus size={16}/>Add teammate</button></div><div className="team">{team.map(a=><article className="agent" key={a[0]}><i style={{background:a[3]}}>{a[0][0]}</i><h3>{a[0]}</h3><p>{a[1]}</p><b><span style={{background:a[3]}}/> {a[2]}</b><small>Working on <strong>Acme customer portal</strong></small></article>)}</div></section>}
function Delivery({tasks}:{tasks:string[][]}){return <section className="board">{['Ready','In progress','Review','Complete'].map(col=><div className="column" key={col}><h3>{col}<b>{col==='Ready'?2:1}</b></h3>{tasks.filter((_,i)=>col==='Ready'?i===3:col==='In progress'?i===0||i===2:col==='Review'?i===1:false).map((t,i)=><article key={i}><em>{t[3]}</em><h4>{t[0]}</h4><span><i>{t[1][0]}</i><Clock3 size={13}/> Today</span></article>)}{col==='Complete'&&<p>✓<br/>Tasks land here when quality gates pass.</p>}</div>)}</section>}
function Marketing(){return <section className="split projects"><article className="panel campaign"><p><Megaphone size={14}/> GROWTH STUDIO</p><h2>Turn delivery into demand.</h2><span>Build credible marketing around the work your office ships: positioning, case studies, launch copy, and content plans.</span><button className="primary">Create campaign <ArrowUpRight size={16}/></button></article><article className="panel"><Title text="Launch kit · Customer portal" action="Open"/>{['Positioning statement','Landing page narrative','Customer story outline','LinkedIn launch sequence'].map((x,i)=><div className="market" key={x}><Megaphone size={17}/><span>{x}<small>{i<1?'Ready for review':i===1?'In progress':'Queued'}</small></span><ChevronRight size={16}/></div>)}</article></section>}
function Metric({icon,name,value,detail}:{icon:ReactNode,name:string,value:string,detail:string}){return <article className="metric"><i>{icon}</i><div><p>{name}</p><h2>{value}</h2><small>{detail}</small></div></article>};function Title({text,action}:{text:string,action:string}){return <div className="title"><h2>{text}</h2><button>{action}<ChevronRight size={14}/></button></div>};function Row({who,color,text,time}:{who:string,color:string,text:string,time:string}){return <div className="row"><i className={color}>{who}</i><span><b>{who==='A'?'Atlas':who==='Q'?'Quinn':who==='N'?'Nova':'Maya'}</b> {text.replace(/^[A-Za-z]+ /,'')}<small>{time}</small></span></div>};function Engage({title,text,due}:{title:string,text:string,due:string}){return <div className="engage"><i><Code2 size={17}/></i><span><b>{title}</b><small>{text}</small></span><em>{due}</em></div>}
